### ISSUE TITLE
add a pre-screener to test any screener dependent columns exist

### ISSUE THREAD

**Issue by lauraselby** [lauraselby/data-screener#25]
For example, if the file does not have time_period, time_identifier and (perhaps) geographic_level the .rmd will not knit. 

tested with a file that had [time; year; level] which is where the problem became apparent

**Comment by cjrace** [comment]
Note to self: combine with #18 and #31 to wrap the knitting of the output into a function that checks for the 5 compulsory columns in the data file, as well as the compulsory columns in the metadata, and, if they fail, outputs a message in the console. Can then chop those tests from the main screener as well.
